version: "3.8"

services:
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: mend
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  mend:
    build: .
    depends_on:
      - "db"
    command: ./test/wait-for-it.sh db:5432 -- ./test/test.sh
