name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install meson
      run: sudo apt install meson
    - name: install postgres
      run: sudo apt install postgresql
    - name: configure
      run: meson build
    - name: build
      run: ninja -C build
    - name: test
      run: initdb
      run: sudo systemctl start postgresql.service
      run: ninja -C build test
