name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build docker-compose stack
      run: docker-compose up --exit-code-from mend --build mend
